# GraphRAG 知识库系统 - 基础服务 Docker Compose 配置
# 包含 PostgreSQL、Neo4j、Redis、MinIO、Weaviate、MinerU 等基础服务
# 作者: GraphRAG Team
# 创建时间: 2024

version: '3.8'

services:
  # PostgreSQL 数据库 - 用于存储文档元数据和文本块
  postgres:
    image: postgres:15-alpine
    container_name: graphrag_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-graphrag}
      POSTGRES_USER: ${POSTGRES_USER:-graphrag}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-graphrag123}
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts/postgres:/docker-entrypoint-initdb.d
    networks:
      - graphrag_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-graphrag} -d ${POSTGRES_DB:-graphrag}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Neo4j 图数据库 - 用于存储实体关系图
  neo4j:
    image: neo4j:5.15-community
    container_name: graphrag_neo4j
    restart: unless-stopped
    environment:
      NEO4J_AUTH: ${NEO4J_USER:-neo4j}/${NEO4J_PASSWORD:-neo4j123}
      NEO4J_dbms_default__database: ${NEO4J_DATABASE:-graphrag}
      NEO4J_dbms_security_procedures_unrestricted: gds.*,apoc.*
      NEO4J_dbms_security_procedures_allowlist: gds.*,apoc.*
      NEO4J_dbms_memory_heap_initial__size: 512m
      NEO4J_dbms_memory_heap_max__size: 2G
      NEO4J_dbms_memory_pagecache_size: 1G
    ports:
      - "7474:7474"  # HTTP
      - "7687:7687"  # Bolt
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_import:/var/lib/neo4j/import
      - neo4j_plugins:/plugins
    networks:
      - graphrag_network
    healthcheck:
      test: ["CMD", "cypher-shell", "-u", "${NEO4J_USER:-neo4j}", "-p", "${NEO4J_PASSWORD:-neo4j123}", "RETURN 1"]
      interval: 10s
      timeout: 10s
      retries: 5

  # Redis 缓存 - 用于缓存和会话管理
  redis:
    image: redis:7-alpine
    container_name: graphrag_redis
    restart: unless-stopped
    command: redis-server --requirepass ${REDIS_PASSWORD:-redis123} --maxmemory 256mb --maxmemory-policy allkeys-lru
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - graphrag_network
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5

  # MinIO 对象存储 - 用于存储原始文档和处理后的文件
  minio:
    image: minio/minio:latest
    container_name: graphrag_minio
    restart: unless-stopped
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minioadmin}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-minioadmin123}
    ports:
      - "9000:9000"  # API
      - "9001:9001"  # Console
    volumes:
      - minio_data:/data
    networks:
      - graphrag_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  # Weaviate 向量数据库 - 用于语义搜索和向量存储
  weaviate:
    command:
    - --host
    - 0.0.0.0
    - --port
    - '8080'
    - --scheme
    - http
    image: cr.weaviate.io/semitechnologies/weaviate:1.33.0
    container_name: graphrag_weaviate
    restart: on-failure:0
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'none'
      # 优化模块配置，减少不必要的模块以避免多向量空间警告
      ENABLE_MODULES: 'text2vec-ollama,generative-ollama'
      CLUSTER_HOSTNAME: 'node1'
      # 添加性能优化配置
      LIMIT_RESOURCES: 'false'
      GOMAXPROCS: '4'
    ports:
      - "8080:8080"
      - "50051:50051"  # gRPC 端口
    volumes:
      - weaviate_data:/var/lib/weaviate
    networks:
      - graphrag_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/v1/.well-known/ready"]
      interval: 10s
      timeout: 5s
      retries: 5

  # MinerU 文档解析服务 - 用于 PDF 和文档处理
  # mineru:
  #   image: opendatalab/mineru:latest
  #   container_name: graphrag_mineru
  #   restart: unless-stopped
  #   environment:
  #     - PYTHONPATH=/app
  #   ports:
  #     - "8501:8501"  # Streamlit 界面
  #   volumes:
  #     - mineru_data:/app/data
  #     - mineru_output:/app/output
  #     - ./configs/mineru:/app/configs
  #   networks:
  #     - graphrag_network
  #   healthcheck:
  #     test: ["CMD", "curl", "-f", "http://localhost:8501/_stcore/health"]
  #     interval: 30s
  #     timeout: 10s
  #     retries: 3
  #   depends_on:
  #     - minio

# 数据卷定义
volumes:
  postgres_data:
    driver: local
  neo4j_data:
    driver: local
  neo4j_logs:
    driver: local
  neo4j_import:
    driver: local
  neo4j_plugins:
    driver: local
  redis_data:
    driver: local
  minio_data:
    driver: local
  weaviate_data:
    driver: local
  # mineru_data:
  #   driver: local
  # mineru_output:
  #   driver: local

# 网络定义
networks:
  graphrag_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16